### PR TITLE
Joy Con

### PR DESCRIPTION
**Pull request by m12watanabe1a**
Controll MG400 via PlayStation 5 Controller

- [x] Base Component
- [x] Clear Error via `circle_btn`
- [x] Call Jog service via `lstick_x`, `lstick_y`, `rstick_x`, `rstick_y` (MG400 has 4 axis, so it corresponds to each)
- [x] Behavior check with hardware

If you have any other good idea please give me the suggestions.

### CODE REVIEW

**Comment by m12watanabe1a** [comment]
You Launch Joy Controller node via following launch file
```bash
ros2 launch mg400_bringup joy.launch.py
```
This just show the joy con input to the terminal, So you need to call service at this line.

https://github.com/HarvestX/MG400_ROS2/blob/features/joy/mg400_control/src/mg400_joy/component.cpp#L39-L41

**Comment by m12watanabe1a** [comment]
Jog service server is implemented here
https://github.com/HarvestX/MG400_ROS2/blob/main/mg400_control/src/mg400_control/component.cpp#L1289

**Comment by kobayashi-na** [comment]
I have just finished implementation of clear_error.
In the part of check whether it catch the response or not, I referred the cord below. (To be honest, I do not understand the use of type <future> very much)
https://github.com/ros2/demos/blob/master/demo_nodes_cpp/src/services/add_two_ints_client_async.cpp

**Comment by kobayashi-na** [comment]
@m12watanabe1a 
I have finished the move_jog task and that's all for this pull request.
Please check them.

**Comment by kobayashi-na** [comment]
@m12watanabe1a 
I tested this program with the hardware and find that the service name is different between MG400_Mock and MG400_Ros2 (ex: /clear_error in Mock is named /mg400/clear_error in Ros2).
https://github.com/HarvestX/MG400_ROS2/blob/features/joy/mg400_control/src/mg400_joy/component.cpp#L28-L29
The code above called the services named /clear_error which is used in Mock.
So, I changed it "/mg400/clear_error" and checked it activate the dobot successfully.
In my opinion, it needs to move on Mock and Ros2 with same code.
Do you know the way to call service name dynamically?

**Comment by m12watanabe1a** [comment]
↑ We discussed on Google meet and then I answered the question at that time.

The namespace of ROS2 system doesn't affect on TCP packet to the Dobot MG400, so the namespace different cant be an issue.

**Pull request merged**
